name: webgltest
description: Trying to use WebGL with Dart
dependencies:
  vector_math: any
  test: any
  barback: any
transformers:
- webgltest/shader_loader
-  $dart2js:
     commandLineOptions: [--enable-experimental-mirrors]				
